spring:
  security:
    oauth2:
      client:
        provider:
          my-server:
            authorization-uri: http://localhost:8080/oauth/authorize
#        registration:
#          my-server:
#            provider: my-server
#            client-id: my-server-frontend
#            client-secret: secret123