spring:
  jackson:
    default-property-inclusion: non_null
  security:
    oauth2:
      keystore: classpath:/jwt.jks
      client-name: Internal Application
  ldap:
    embedded:
      base-dn: dc=springframework,dc=org
      credential:
        username: uid=admin,ou=people,dc=springframework,dc=org
        password: password
  redis:
    embedded:
      enabled: true
